---
- name: install lazygit
  community.general.pacman:
    executable: pacman
    reason: explicit
    reason_for: all
    state: latest
    update_cache: true
    name:
      - lazygit

- name: symlink lazygit config file
  ansible.builtin.include_role:
    name: symlink
  vars:
    dst: "{{ ansible_env.HOME }}/.config/lazygit"
