---
- name: install btop
  community.general.pacman:
    executable: pacman
    reason: explicit
    reason_for: all
    state: latest
    update_cache: true
    name:
      - btop

- name: symlink btop config file
  ansible.builtin.include_role:
    name: symlink
  vars:
    dst: "{{ ansible_env.HOME }}/.config/btop"

